# master branch commits deploy on NuGet as beta

-
  branches:
    only:
      - develop

  version: 2.10.{build}

  environment:
    packageVersion: $env:buildVersion

  init:
    - ps: |
        $version = new-object System.Version $env:APPVEYOR_BUILD_VERSION
        $env:PackageVersion = "{0}.{1}.{2}-beta" -f $version.Major, $version.Minor, $version.Build

  assembly_info:
    patch: true
    file: '**\AssemblyInfo.*'
    assembly_version: '$(APPVEYOR_BUILD_VERSION)'
    assembly_file_version: '$(APPVEYOR_BUILD_VERSION)'
    assembly_informational_version: '$(PackageVersion)'

  configuration: Release

  nuget:
    account_feed: true
    project_feed: true
    disable_publish_on_pr: true


  before_build:
    - nuget restore

  build_script:
    - msbuild SchwabenCode.QuickIO.sln /m /verbosity:minimal /p:Configuration=Release /p:Platform="Any CPU"
    - msbuild SchwabenCode.QuickIO.sln /m /verbosity:minimal /p:Configuration=RELEASE_NET40 /p:Platform="Any CPU"
    - msbuild SchwabenCode.QuickIO.sln /m /verbosity:minimal /p:Configuration=RELEASE_NET45 /p:Platform="Any CPU"
    - msbuild SchwabenCode.QuickIO.sln /m /verbosity:minimal /p:Configuration=RELEASE_NET46 /p:Platform="Any CPU"

  after_build:
  - ps: nuget pack SchwabenCode.QuickIO.nuspec -version "$env:PackageVersion"

  test:
    assemblies:
      - 'tests\**\*.UnitTests.dll'
      - 'tests\**\*.IntegrationTests.dll'

  artifacts:
  - path: 'QuickIO.NET.*.nupkg'
    name: SchwabenCode.QuickIO-NuGetPackage

  deploy:
    - provider: NuGet
      server: https://www.myget.org/F/schwabencode/api/v2/package
      api_key:
        secure: 5r4u1BFGZ9CjakS0ATOT2sAKcOjJ7BHzRYJC88aQnYOplsCsKYVtwcTEIGNzHOdh
      artifact: SchwabenCode.QuickIO-NuGetPackage

# release branch
-
  branches:
    only:
    - master

  version: 2.10.{build}

  environment:
    packageVersion: $env:buildVersion

  init:
    - ps: |
        $version = new-object System.Version $env:APPVEYOR_BUILD_VERSION
        $env:PackageVersion = "{0}.{1}.{2}" -f $version.Major, $version.Minor, $version.Build

  assembly_info:
    patch: true
    file: '**\AssemblyInfo.*'
    assembly_version: '$(APPVEYOR_BUILD_VERSION)'
    assembly_file_version: '$(APPVEYOR_BUILD_VERSION)'
    assembly_informational_version: '$(PackageVersion)'

  configuration: Release

  nuget:
    account_feed: true
    project_feed: true
    disable_publish_on_pr: true


  before_build:
    - nuget restore

  build_script:
    - msbuild SchwabenCode.QuickIO.sln /m /verbosity:minimal /p:Configuration=Release /p:Platform="Any CPU"
    - msbuild SchwabenCode.QuickIO.sln /m /verbosity:minimal /p:Configuration=RELEASE_NET40 /p:Platform="Any CPU"
    - msbuild SchwabenCode.QuickIO.sln /m /verbosity:minimal /p:Configuration=RELEASE_NET45 /p:Platform="Any CPU"
    - msbuild SchwabenCode.QuickIO.sln /m /verbosity:minimal /p:Configuration=RELEASE_NET46 /p:Platform="Any CPU"

  test:
    assemblies:
      - 'tests\**\*.UnitTests.dll'
      - 'tests\***\*.IntegrationTests.dll'

  after_build:
  - ps: nuget pack SchwabenCode.QuickIO.nuspec -version "$env:PackageVersion"

  artifacts:
  - path: 'QuickIO.NET.*.nupkg'
    name: SchwabenCode.QuickIO-NuGetPackage

  deploy:
    - provider: NuGet
      api_key:
        secure: 1A6ODONpTd1O0+/7ojwfX8H1aAto/Wvqb9RdKg2oKk/FDaKedTXXi9azFBxumdku
      artifact: SchwabenCode.QuickIO-NuGetPackage
      on:
        branch: master
        appveyor_repo_tag: true

# all other branches
# compile, test, release
-
  version: 2.10.{build}

  configuration: Release

  before_build:
  - nuget restore

  build:
    verbosity: minimal
    project: SchwabenCode.QuickIO.sln