# develop branch commits: build, test and deploy on MyGet as pre-release
# master branch commits without tag: no deploy, just build and test
# master branch commits with tag (GitHub release): build, test and deploy on Nuget as stable
-
  branches:
    only:
      - develop

  version: 2.10.{build}

  environment:
    packageVersion: $env:buildVersion

  init:
    - ps: |
        $version = new-object System.Version $env:APPVEYOR_BUILD_VERSION
        $env:PackageVersion = "{0}.{1}.{2}-beta" -f $version.Major, $version.Minor, $version.Build

  assembly_info:
    patch: true
    file: '**\AssemblyInfo.*'
    assembly_version: '$(APPVEYOR_BUILD_VERSION)'
    assembly_file_version: '$(APPVEYOR_BUILD_VERSION)'
    assembly_informational_version: '$(PackageVersion)'

  configuration: Release

  nuget:
    account_feed: true
    project_feed: true
    disable_publish_on_pr: true


  before_build:
    - nuget restore

  build:
    verbosity: minimal
    project: SchwabenCode.QuickIO.sln

  after_build:
  - ps: nuget pack SchwabenCode.QuickIO.nuspec -version "$env:PackageVersion"

  test:
    assemblies:
      - 'test\**\*.UnitTests.dll'
      - 'test\**\*.IntegrationTests.dll'

  artifacts:
  - path: 'QuickIO.NET.*.nupkg'
    name: SchwabenCode.QuickIO-NuGetPackage

  deploy:
    - provider: NuGet
      server: https://www.myget.org/F/schwabencode/api/v2/package
      api_key:
        secure: 5r4u1BFGZ9CjakS0ATOT2sAKcOjJ7BHzRYJC88aQnYOplsCsKYVtwcTEIGNzHOdh
      artifact: SchwabenCode.QuickIO-NuGetPackage

-
  branches:
    only:
    - master

  version: 2.10.{build}

  environment:
    packageVersion: $env:buildVersion

  init:
    - ps: |
        $version = new-object System.Version $env:APPVEYOR_BUILD_VERSION
        $env:PackageVersion = "{0}.{1}.{2}" -f $version.Major, $version.Minor, $version.Build

  assembly_info:
    patch: true
    file: '**\AssemblyInfo.*'
    assembly_version: '$(APPVEYOR_BUILD_VERSION)'
    assembly_file_version: '$(APPVEYOR_BUILD_VERSION)'
    assembly_informational_version: '$(PackageVersion)'

  configuration: Release

  nuget:
    account_feed: true
    project_feed: true
    disable_publish_on_pr: true


  before_build:
    - nuget restore

  build:
    verbosity: minimal
    project: SchwabenCode.QuickIO.sln

  test:
    assemblies:
      - 'tests\**\*.UnitTests.dll'
      - 'tests\***\*.IntegrationTests.dll'

  after_build:
  - ps: nuget pack SchwabenCode.QuickIO.nuspec -version "$env:PackageVersion"

  artifacts:
  - path: 'QuickIO.NET.*.nupkg'
    name: SchwabenCode.QuickIO-NuGetPackage

  deploy:
    - provider: NuGet
      api_key:
        secure: 1A6ODONpTd1O0+/7ojwfX8H1aAto/Wvqb9RdKg2oKk/FDaKedTXXi9azFBxumdku
      artifact: SchwabenCode.QuickIO-NuGetPackage
      on:
        branch: master
        appveyor_repo_tag: true

# all other branches
# compile, test
-
  version: 2.10.{build}

  configuration: Release

  before_build:
  - nuget restore

  build:
    verbosity: minimal
    project: SchwabenCode.QuickIO.sln
